export const ADD_PROJECT_REQUIST = "ADD_PROJECT_REQUIST"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL"

export const GET_PROJECTS_REQUIST = "GET_PROJECTS_REQUIST"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL"

export const DELETE_PROJECT_REQUIST = "DELETE_PROJECT_REQUIST"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL"

export const GET_PROJECT_DETAILS_REQUIST = "GET_PROJECT_DETAILS_REQUIST"
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS"
export const GET_PROJECT_DETAILS_FAIL = "GET_PROJECT_DETAILS_FAIL"