export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNIN_REQUIST = 'USER_SIGNIN_REQUIST';
export const USER_SIGNIN_DATAERROR = 'USER_SIGNIN_DATAERROR';




export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_REQUIST = 'USER_REGISTER_REQUIST';
export const USER_REGISTER_DATAERROR = 'USER_REGISTER_DATAERROR';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';

export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const CLEAR_UPDATE_PROFILE = 'CLEAR_UPDATE_PROFILE';

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL';
export const CLEAR_UPDATE_IMAGE = 'CLEAR_UPDATE_IMAGE';
export const GET_IMAGE = 'GET_IMAGE';


export const LIST_USERS_REQUEST = 'LIST_USERS_REQUEST';
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS';
export const LIST_USERS_FAIL = 'LIST_USERS_FAIL';


export const DELETE_USER = 'DELETE_USER';



